{{- $fluentd := index .Packages "fluentd" -}}

source 'https://rubygems.org'

gem 'fluentd', '<={{ $fluentd.Version }}'
gem 'activesupport'
gem 'fluent-plugin-kubernetes_metadata_filter'
gem 'fluent-plugin-elasticsearch'
gem 'fluent-plugin-systemd'
gem 'fluent-plugin-detect-exceptions'
gem 'fluent-plugin-prometheus'
gem 'fluent-plugin-multi-format-parser'
gem 'oj'
